component: scf
name: ap-guangzhou_default_Kafka_To_Cos
org: app
app: Kafka_To_Cos
stage: dev
inputs:
  name: Kafka_To_Cos
  src: ./
  description: 本範例通過配置kafka觸發器，從kafka接收到訊息後，寫入文件並上傳到cos中
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  events:
    - ckafka: # ckafka觸發器
        name: # input Ckafka  trigger name
        parameters:
          name: # input Ckafka Instance id        
          topic: # input Ckafka Topic name  
          maxMsgNum: 100
          offset: latest
          enable: true