component: scf
name: ap-guangzhou_default_Thumbnail
org: app
app: Thumbnail
stage: dev
inputs:
  name: Thumbnail
  src: ./
  description: >-
    This demo need to config COS trigger. When object has been upload to COS
    bucket, the SCF will download it to /tmp and compress it. 本範例配置了 COS
    觸發器，當有文件上傳到對應的 COS bucket時，會觸發雲函數執行，并把文件下載到本地臨時目錄，用做後續處理
  handler: Thumbnail.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  events:
     - cos: # cos觸發器
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true

