component: scf
name: ap-guangzhou_default_ES_curator_clear
org: app
app: ES_curator_clear
stage: dev
inputs:
  name: ES_curator_clear
  src: ./
  description: >-
    This demo uses ElasticSearch curator and timer trigger to clear index of ES.
    通過使用 ElasticSearch curator 庫，實現了 ES 索引的删除清理。可爲其配置定時觸發器後，定時執行並清理 ES 内索引
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 10