component: scf
name: ap-guangzhou_default_API_GW_WebPage_Demo
org: app
app: API_GW_WebPage_Demo
stage: dev
inputs:
  name: API_GW_WebPage_Demo
  src: ./
  description: >-
    This demo is mainly to show how to set up personal web page in serverless
    with apigateway. 本範例主要通過 SCF 結合 API 閘道，快速實現一個對公網服務的 Web 頁面。
  handler: index.main_handler
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  events:
     - apigw: # api閘道觸發器
        name: serverless
        serviceId: # input API gateway serviceId
        parameters:
          protocols:
            - http
          description: the serverless service
          environment: release
          endpoints:
            - path: /
              method: GET
              function:
                isIntegratedResponse: TRUE