component: scf
name: ap-guangzhou_default_unpack_to_cos
org: app
app: unpack_to_cos
stage: dev
inputs:
  name: unpack_to_cos
  src: ./
  description: >-
    上傳壓縮包至COS時，可觸發雲函數下載壓縮包并解壓，然後将解壓縮後的文件上傳至另一個 COS 儲存桶
  handler: index.main_handler
  runtime: Nodejs10.15
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 900
  events:
     - cos: # cos觸發器
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true