component: scf
name: ap-guangzhou_default_api_service
org: app
app: api_service
stage: dev
inputs:
  name: api_service
  src: ./
  description: >-
    This demo uses API GW to provide API service. You can expand to do WEB API
    based on this. 本範例演示基于API閘道提供博客内的文章查詢和文章内容，您可以擴展函數來實現 Web 後端服務
  handler: api_service.main_handler
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  events:
     - apigw: # api閘道觸發器
        name: serverless
        serviceId: # input API gateway serviceId
        parameters:
          protocols:
            - http
          description: the serverless service
          environment: release
          endpoints:
            - path: /
              method: GET
              function:
                isIntegratedResponse: TRUE
