component: scf
name: ap-guangzhou_default_idcard_detection
org: app
app: idcard_detection
stage: dev
inputs:
  name: idcard_detection
  src: ./
  description: idcard_detection. 本範例使用 COS 觸發器，並調用AI介面實現身份證識别
  handler: idcard_detection.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  events:
     - cos: # cos觸發器
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true