component: scf
name: ap-guangzhou_default_helloworld
org: app
app: helloworld
stage: dev
inputs:
  name: helloworld
  src: ./
  description: helloworld blank template function. Helloworld空白範本函數
  handler: index.main_handler
  runtime: CustomRuntime
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3