component: scf
name: ap-guangzhou_default_Ckafka To Elasticsearch
org: app
app: Ckafka To Elasticsearch
stage: dev

inputs:
  name: Ckafka_To_Elasticsearch
  src: ./
  description: >-
    This demo will connect Ckafca and consume message automatically. The SCF
    will write each message to txt by each line. Then SCF will name this file by
    time and upload this txt to COS bucket.
    使用Ckafka+雲函數+ES+Kibana，提供日志轉存和清洗能力，替代Logstash，成本更低，支援功能自定義。
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 30
  events:
    - ckafka: # ckafka觸發器
        name: # input Ckafka  trigger name
        parameters:
          name: # input Ckafka Instance id        
          topic: # input Ckafka Topic name  
          maxMsgNum: 100
          offset: latest
          enable: true