component: scf
name: ap-guangzhou_default_QRcodewithLogo
org: app
app: QRcodewithLogo
stage: dev
inputs:
  name: QRcodewithLogo
  src: ./
  description: >-
    This demo is mainly to show how to use resources, how to get values from the
    web users, and how to return a web or a file.
    本範例主要展示在SCF中對各種資源的引用方法，包括include
    php文件、調用上傳到SCF中的非php文件、使用/tmp臨時目錄，同時展示了SCF中3種獲取用戶提交數據的方法，最後演示如何返回一個網頁或文件。
  handler: index.main_handler
  runtime: Php7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 10
  events:
     - apigw: # api閘道觸發器
        name: serverless
        serviceId: # input API gateway serviceId
        parameters:
          protocols:
            - http
          description: the serverless service
          environment: release
          endpoints:
            - path: /
              method: GET
              function:
                isIntegratedResponse: TRUE
